### PR TITLE
Add IntelliJ configuration files

### PR DESCRIPTION
**Pull request by youssefsoli**
This is a quick patch that adds git-safe Intellij configuration files so that the project can work out of the box when using Intellij.

### CODE REVIEW

**Review by Ludosss — APPROVED** [review]
minor changes look good

**Review by jpablo2002 — APPROVED** [review]
Great change to allow the project to be ran with minimal configuration and effort. Looks great!

**Review by JacketPants12 — APPROVED** [review]
Intellij config

**Comment by youssefsoli** [comment]
Turns out this change causes more issues that it fixes, closing.

**Pull request closed without merging**
