### PR TITLE
Added Unit and Integration Tests

### PR DESCRIPTION
**Pull request by JacketPants12**
- Created BaseTest class
 - Create ControllerBaseTest class
 - Created UserProfileControllerIntegrationTest class
 - Create UserProfileServiceTest class
 - Added delete method to repositories
 - Added application-test.properties

### CODE REVIEW

**Review by youssefsoli — CHANGES_REQUESTED** [review]
Just some minor changes are needed.

**Comment by JacketPants12** [comment]
> What is the purpose of classes BaseTest and ControllerBaseIntegrationTest?

Base test is for any setup that is shared by all tests.
ControllerBaseIntegrationTest same logic. For example there is no need to have code the setup MockMvc in every integration test class.

**Review by modaserMoj — APPROVED** [review]
The test files correctly test the use case and the code follows the conventions

**Review by feiwun — APPROVED** [review]
the files changed address the intended purposes as needed

**Review by youssefsoli — APPROVED** [review]
Everything looks good since my last comments, this testing structure should be helpful for everyone to use.

**Pull request merged**
