### PR TITLE
[Refactor] Switch to hexagonal architecture

### PR DESCRIPTION
**Pull request by youssefsoli**
This PR brings a change to the file structure to the project for easier development.

### CODE REVIEW

**Comment by youssefsoli** [comment]
I also cleaned up our entities with Lombok for more readability.

**Review by JacketPants12 — APPROVED** [review]
Lombok significantly shortened the amount of boilerplate code that needed to be written for the project. This made the project more readable and maintainable. In addition, switching to hexagonal architecture made the project more testable and easier to extend.

**Review by modaserMoj — APPROVED** [review]

**Review by jpablo2002 — APPROVED** [review]
The new instance of clean architecture, hexagonal, and its file structure is very intuitive and easy to understand, making it so that anyone can easily analyze the different parts of the project. Looks good to me!

**Review by modaserMoj — COMMENTED** [review]
The use of lombok greatly reduces repetitive code which makes reading files a lot easier and overall clearer.

**Pull request merged**
