### PR TITLE
User follow usecase

### PR DESCRIPTION
**Pull request by jannater**
This pull request adds a use case for follow. The use case takes the data from the controller. It then takes the follower ID and adds it to the FollowerIDList. The followee ID and adds it to the FolloweeIDList. It also throws an error for when a user tries to follow themselves. Finally the ID of the followee is returned.

### CODE REVIEW

**Review by feiwun — APPROVED** [review]
followed clean architecture well. add documentation to further explain your process and clean up code where necessary

**Comment by youssefsoli** [comment]
The branch needs to be rebased before merging, otherwise, everything looks good.\

**Review by youssefsoli — APPROVED** [review]
Everything looks good.

**Review by jpablo2002 — APPROVED** [review]
Everything looks good to me.

**Review by modaserMoj — APPROVED** [review]
Code seems well with respect to all the clean and other guidelines

**Review by JacketPants12 — APPROVED** [review]
lgtm

**Pull request merged**
